### ISSUE TITLE
请问能把已经接完的资源列出一份文档出来么

### ISSUE THREAD

**Issue by mingmingshiliyu** [yunionio/cloudmux#453]

**Comment by ioito** [comment]
https://github.com/yunionio/cloudmux/blob/master/pkg/cloudprovider/resources.go
https://github.com/yunionio/cloudmux/blob/master/pkg/cloudprovider/cloudprovider.go
接入的云资源都以接口方式实现，对于具体的云资源是否实现，可以直接搜索对应的接口是否实现

**Comment by mingmingshiliyu** [comment]
> https://github.com/yunionio/cloudmux/blob/master/pkg/cloudprovider/resources.go https://github.com/yunionio/cloudmux/blob/master/pkg/cloudprovider/cloudprovider.go 接入的云资源都以接口方式实现，对于具体的云资源是否实现，可以直接搜索对应的接口是否实现 @mingmingshiliyu

部分方法注释了，比如安全组，还可用么，而且大部分都是查询，创建更新能力是没有完全在这里列出来还是需要自己实现

**Comment by ioito** [comment]
> > https://github.com/yunionio/cloudmux/blob/master/pkg/cloudprovider/resources.go https://github.com/yunionio/cloudmux/blob/master/pkg/cloudprovider/cloudprovider.go 接入的云资源都以接口方式实现，对于具体的云资源是否实现，可以直接搜索对应的接口是否实现 @mingmingshiliyu
> 
> 部分方法注释了，比如安全组，还可用么，而且大部分都是查询，创建更新能力是没有完全在这里列出来还是需要自己实现

是的，如果二次开发需要自己加接口并实现
