### ISSUE TITLE
能否新增最新的版本至go mod

### ISSUE THREAD

**Issue by wuchenzh** [yunionio/cloudmux#463]
目前只有
v0.3.10-0-alpha.1
v0.3.10-0-alpha.0

**Comment by wuchenzh** [comment]
go.mod:8:2: require yunion.io/x/cloudmux: version "v3.10.6-20231009.2" invalid: should be v0 or v1, not v3

不行额

**Comment by ioito** [comment]
https://github.com/yunionio/cloudpods/blob/master/go.mod @wuchenzh 你可以看下cloudpods是怎么引用的

**Comment by wuchenzh** [comment]
ok 谢谢
